<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Levent Bulut">

<title>Surya Vadhan - Mini Group Project 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/surya.jpg" rel="icon" type="image/jpeg">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Surya Vadhan</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html" rel="" target="">
 <span class="menu-text">Resume</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Mini Group Project 1</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Levent Bulut </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="business-problem" class="level1">
<h1>Business Problem</h1>
<p>In this group project, you will work with analysts’ forecast data of earning per share (EPS) provided by Wharton Research Data Services (WRDS). Institutional Brokers’ Estimate System (I/B/E/S) provides historical data on certain financial indicators collected from thousands of individual analysts working in more than 3,000 broker houses.</p>
<ul>
<li><p><strong>TICKER:</strong> A unique identifier assigned to each security. In this group project, you will only model “NFLX” ticker.</p></li>
<li><p><strong>CNAME:</strong> Company name</p></li>
<li><p><strong>ACTDATS:</strong> The Activation date: It is the date when the analyst forecast became effective within the IBES database.</p></li>
<li><p><strong>ESTIMATOR:</strong> Sellside institution (mostly broker house). It is just the broker.</p></li>
<li><p><strong>ANALYS:</strong> The person who makes the forecast and work for sellside institution. Estimators and analysts are represented by codes to hide their real names.</p></li>
<li><p><strong>FPI:</strong> Forecast Period Indicator: The forecasting period. 6: Next Fiscal Quarter 1: Next Fiscal Year</p></li>
<li><p><strong>MEASURE</strong>: The variable being estimated. We have data for earning per share (EPS)</p></li>
<li><p><strong>VALUE:</strong> The forecasted value of EPS</p></li>
<li><p><strong>FPEDATS</strong>: The Forecast Period End Date: It is the ending date of the fiscal period to which the estimate applies. For the majority of companies, the FPEDATS date is December 31st of that year.</p></li>
<li><p><strong>REVDATS:</strong> The Review Date: It is the most recent date on which IBES called the analyst and verified that particular estimate as still valid for that analyst. If an analyst confirms that a previous estimate is still valid, the original database record for that estimate is retained and only the REVDATS variable is updated. If an analyst changes their estimate for a given company, a new record is entered in the database with a new ANNDATS. The old record of the analyst (containing the previous estimate) is retained in the database.</p></li>
<li><p><strong>REVTIMS</strong>: Time-stamp of REVDATS</p></li>
<li><p><strong>ANNDATS</strong>: The Announce date: It is the date on which the analyst first made that particular estimate.</p></li>
<li><p><strong>ANNTIMS</strong>: Time-stamp of ANNDATS</p></li>
<li><p><strong>ACTUAL</strong>: The realized EPS, the true EPS value.</p></li>
<li><p><strong>ANNDATS_ACT</strong>: The Announced date of Actual EPS: The actual EPS value is announced by the company at this date.</p></li>
<li><p><strong>ANNTIMS_ACT</strong>: The time-stamp of ANNDATS_ACT</p></li>
</ul>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"data.table"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"data.table"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'data.table'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:dplyr':

    between, first, last</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kableExtra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'reshape2'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:data.table':

    dcast, melt</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:tidyr':

    smiths</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read CSV file</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>NFLX <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:/Users/HP/Downloads/NFLX.csv"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display column names</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(NFLX)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "TICKER"      "CNAME"       "ACTDATS"     "ESTIMATOR"   "ANALYS"     
 [6] "FPI"         "MEASURE"     "VALUE"       "FPEDATS"     "REVDATS"    
[11] "REVTIMS"     "ANNDATS"     "ANNTIMS"     "ACTUAL"      "ANNDATS_ACT"
[16] "ANNTIMS_ACT"</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View first rows</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(NFLX)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  TICKER        CNAME  ACTDATS ESTIMATOR ANALYS FPI MEASURE   VALUE  FPEDATS
1   NFLX NETFLIX INC. 20020812      1872   6749   6     EPS -0.0086 20020930
2   NFLX NETFLIX INC. 20020812       183  79868   6     EPS -0.0029 20020930
3   NFLX NETFLIX INC. 20020812       220  57596   6     EPS -0.0100 20020930
4   NFLX NETFLIX INC. 20021009       183  79868   6     EPS -0.0050 20020930
5   NFLX NETFLIX INC. 20020805       183  79868   1     EPS -0.0250 20021231
6   NFLX NETFLIX INC. 20021202      2178  80485   1     EPS -0.0321 20021231
   REVDATS  REVTIMS  ANNDATS  ANNTIMS ACTUAL ANNDATS_ACT ANNTIMS_ACT
1 20021018 17:02:56 20020809 14:00:00 -7e-04    20021017    17:04:00
2 20021008 13:19:30 20020812 10:54:00 -7e-04    20021017    17:04:00
3 20021018 15:09:01 20020812 12:13:00 -7e-04    20021017    17:04:00
4 20021018 16:46:17 20021009  8:50:00 -7e-04    20021017    17:04:00
5 20021129 11:28:32 20020805 13:47:28 -5e-03    20030115    17:39:00
6 20021202 11:56:50 20021202 11:56:50 -5e-03    20030115    17:39:00</code></pre>
</div>
</div>
<section id="how-to-read-the-data" class="level2">
<h2 class="anchored" data-anchor-id="how-to-read-the-data">How to read the data</h2>
<p><strong>The first row in NFLX data set</strong>: On 09‐Aug-2002 (ANNDATS), analyst 6749 (ANALYS) at Estimator 1872 (ESTIMATOR) predicts that the EPS (MEASURE) for NETFLIX INC. (CNAME) with a ticker of NFLX (TICKER) with forecast period ending 30‐Sep-2002 (FPEDATS) is -$0.0086 (VALUE). This estimates was entered into the database on 12‐Aug-2002 (ACTDATS). On 17-Oct-2002 (ANNDATS_ACT), NETFLIX INC. announced an actual EPS of $7e-04 ($0.0007) (ACTUAL) for this quarter (FPI=6).</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(NFLX,<span class="at">n=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  TICKER        CNAME  ACTDATS ESTIMATOR ANALYS FPI MEASURE   VALUE  FPEDATS
1   NFLX NETFLIX INC. 20020812      1872   6749   6     EPS -0.0086 20020930
   REVDATS  REVTIMS  ANNDATS  ANNTIMS ACTUAL ANNDATS_ACT ANNTIMS_ACT
1 20021018 17:02:56 20020809 14:00:00 -7e-04    20021017    17:04:00</code></pre>
</div>
</div>
</section>
<section id="your-turn" class="level2">
<h2 class="anchored" data-anchor-id="your-turn">Your Turn:</h2>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Task 1A: Calculate Missingness
</div>
</div>
<div class="callout-body-container callout-body">
<p>Check to see the missing values in NFLX dataset and calculate the percent missing for each variable in <code>NFLX</code> and list your findings in R object called <code>NFLX_missingness</code>. <code>NFLX_missingness</code> is a dataframe with two columns: The first column, <code>Variable</code>, stores the variable names and the second column, <code>Missingness</code> shows the percent missing in percentage points with two decimal points.</p>
</div>
</div>
</section>
<section id="your-code-for-task-1a" class="level2">
<h2 class="anchored" data-anchor-id="your-code-for-task-1a">Your code for Task 1A</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read CSV file</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>NFLX <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"C:/Users/HP/Downloads/NFLX.csv"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate missingness manually</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>missingness_percentages <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(<span class="fu">is.na</span>(NFLX)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame with Variable names and MissingPercentage values</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>missing_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Variable =</span> <span class="fu">names</span>(missingness_percentages), <span class="at">MissingPercentage =</span> missingness_percentages)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print missingness percentages</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Missing Values Percentage by Variable"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Missing Values Percentage by Variable"</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>               Variable MissingPercentage
TICKER           TICKER          0.000000
CNAME             CNAME          0.000000
ACTDATS         ACTDATS          0.000000
ESTIMATOR     ESTIMATOR          0.000000
ANALYS           ANALYS          0.000000
FPI                 FPI          0.000000
MEASURE         MEASURE          0.000000
VALUE             VALUE          0.000000
FPEDATS         FPEDATS          0.000000
REVDATS         REVDATS          0.000000
REVTIMS         REVTIMS          0.000000
ANNDATS         ANNDATS          0.000000
ANNTIMS         ANNTIMS          0.000000
ACTUAL           ACTUAL          4.115304
ANNDATS_ACT ANNDATS_ACT          4.115304
ANNTIMS_ACT ANNTIMS_ACT          0.000000</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize missing values with custom color</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>missingness_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Variable, <span class="sc">-</span>MissingPercentage), <span class="at">y =</span> MissingPercentage)) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"#66c2a5"</span>) <span class="sc">+</span>  <span class="co"># Custom color: greenish</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Missing Values Percentage by Variable"</span>, </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Variable"</span>, <span class="at">y =</span> <span class="st">"Missing Percentage"</span>) <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate and display missing values plot</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="fu">missingness_plot</span>(missing_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Task 1B: Data Manipulation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Conduct the following data manipulations on <code>NFLX</code>:</p>
<ul>
<li><p>Drop rows from the data set when a variable has a missing value</p></li>
<li><p>Drop rows from the data set the quarterly forecasts (drop FPI=6)</p></li>
<li><p>Declare TICKER, CNAME, ESTIMATOR , ANALYS, FPI , and MEASURE variables as factor</p></li>
<li><p>Declare ACTDATS, FPEDATS , ANNDATS, REVDATS, ANNDATS_ACT as time variable.</p></li>
<li><p>Drop ANNTIMS_ACT, ANNTIMS , and REVTIMS</p></li>
<li><p>Create a new column named YEAR that captures the year in FPEDATS</p></li>
<li><p>Name your reduced dataset as <code>NFLX1</code></p></li>
<li><p>Print out data structure and the summary of NFLX1</p></li>
</ul>
</div>
</div>
</section>
<section id="your-code-for-task-1b" class="level2">
<h2 class="anchored" data-anchor-id="your-code-for-task-1b">Your code for Task 1B</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Copy NFLX to NFLX1 without assigning data types</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>NFLX1 <span class="ot">&lt;-</span> NFLX</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows from the data set when a variable has a missing value</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>NFLX1 <span class="ot">&lt;-</span> NFLX1 <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>()</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows from the data set where FPI=6</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>NFLX1 <span class="ot">&lt;-</span> NFLX1 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FPI <span class="sc">!=</span> <span class="dv">6</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop ANNTIMS_ACT, ANNTIMS, and REVTIMS</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>NFLX1 <span class="ot">&lt;-</span> NFLX1 <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>ANNTIMS_ACT, <span class="sc">-</span>ANNTIMS, <span class="sc">-</span>REVTIMS)</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column named YEAR that is an exact copy of the data in FPEDATS</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>NFLX1 <span class="ot">&lt;-</span> NFLX1 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">YEAR =</span> FPEDATS)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Print out data structure and the summary of NFLX1</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(NFLX1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'data.table' and 'data.frame':  2603 obs. of  14 variables:
 $ TICKER     : chr  "NFLX" "NFLX" "NFLX" "NFLX" ...
 $ CNAME      : chr  "NETFLIX INC." "NETFLIX INC." "NETFLIX INC." "NETFLIX INC." ...
 $ ACTDATS    : int  20020805 20021202 20021202 20021202 20021205 20030106 20030115 20030116 20030121 20030314 ...
 $ ESTIMATOR  : int  183 2178 1872 220 2178 1872 2227 220 1872 481 ...
 $ ANALYS     : int  79868 80485 6749 57596 80485 6749 82629 57596 6749 81599 ...
 $ FPI        : int  1 1 1 1 1 1 1 1 1 1 ...
 $ MEASURE    : chr  "EPS" "EPS" "EPS" "EPS" ...
 $ VALUE      : num  -0.025 -0.0321 -0.0207 -0.0179 -0.0286 -0.0136 -0.0164 -0.0071 0.0107 0.0129 ...
 $ FPEDATS    : int  20021231 20021231 20021231 20021231 20021231 20021231 20021231 20031231 20031231 20031231 ...
 $ REVDATS    : int  20021129 20021202 20021202 20021206 20021205 20030114 20030115 20030417 20030402 20030409 ...
 $ ANNDATS    : int  20020805 20021202 20021202 20021202 20021204 20030102 20030115 20030116 20030116 20030314 ...
 $ ACTUAL     : num  -0.005 -0.005 -0.005 -0.005 -0.005 -0.005 -0.005 0.0393 0.0393 0.0393 ...
 $ ANNDATS_ACT: int  20030115 20030115 20030115 20030115 20030115 20030115 20030115 20040121 20040121 20040121 ...
 $ YEAR       : int  20021231 20021231 20021231 20021231 20021231 20021231 20021231 20031231 20031231 20031231 ...
 - attr(*, ".internal.selfref")=&lt;externalptr&gt; </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NFLX1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    TICKER             CNAME              ACTDATS           ESTIMATOR   
 Length:2603        Length:2603        Min.   :20020805   Min.   :  11  
 Class :character   Class :character   1st Qu.:20101021   1st Qu.: 192  
 Mode  :character   Mode  :character   Median :20141009   Median : 899  
                                       Mean   :20136831   Mean   :1376  
                                       3rd Qu.:20180122   3rd Qu.:2502  
                                       Max.   :20210119   Max.   :4439  
     ANALYS            FPI      MEASURE              VALUE       
 Min.   :  1047   Min.   :1   Length:2603        Min.   :-0.150  
 1st Qu.: 71755   1st Qu.:1   Class :character   1st Qu.: 0.190  
 Median : 82010   Median :1   Mode  :character   Median : 0.430  
 Mean   : 89534   Mean   :1                      Mean   : 1.339  
 3rd Qu.:114459   3rd Qu.:1                      3rd Qu.: 2.015  
 Max.   :194536   Max.   :1                      Max.   : 7.670  
    FPEDATS            REVDATS            ANNDATS             ACTUAL      
 Min.   :20021231   Min.   :20021129   Min.   :20020805   Min.   :-0.005  
 1st Qu.:20101231   1st Qu.:20110120   1st Qu.:20101021   1st Qu.: 0.250  
 Median :20141231   Median :20141013   Median :20141009   Median : 0.430  
 Mean   :20137082   Mean   :20137740   Mean   :20136830   Mean   : 1.384  
 3rd Qu.:20181231   3rd Qu.:20180122   3rd Qu.:20180122   3rd Qu.: 2.680  
 Max.   :20201231   Max.   :20210119   Max.   :20210119   Max.   : 6.080  
  ANNDATS_ACT            YEAR         
 Min.   :20030115   Min.   :20021231  
 1st Qu.:20110126   1st Qu.:20101231  
 Median :20150120   Median :20141231  
 Mean   :20145973   Mean   :20137082  
 3rd Qu.:20190117   3rd Qu.:20181231  
 Max.   :20210119   Max.   :20201231  </code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Task 2: Calculate Number of Analysts and Brokerage Houses
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Calculate the total number of <strong>unique</strong> analysts in <strong>NFLX1</strong> dataset that provide forecasts <strong>each year</strong> and name your R object as <strong>NumberAnalyst</strong></p></li>
<li><p>Calculate the total number of <strong>unique</strong> brokerage houses (ESTIMATOR) in <strong>NFLX1</strong> dataset that provide forecasts <strong>each year</strong> and name your R object as <strong>NumberBrokerage</strong></p></li>
<li><p><strong>Need Written Response in this callout:</strong> In which year(s) we have the highest number of unique analysts providing forecasts for NFLX ticker? In which year(s), we have the highest number of unique brokerage houses providing forecasts for the NFLX ticker.</p></li>
</ul>
<p><strong><em><code>2020 is the year December 31 is the month which had the most unique number of analyst providing forecast for NTFLX.</code></em></strong></p>
</div>
</div>
</section>
<section id="your-code-for-task-2" class="level2">
<h2 class="anchored" data-anchor-id="your-code-for-task-2">Your code for Task 2</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column named YEAR</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>NFLX1[, YEAR <span class="sc">:</span><span class="er">=</span> <span class="fu">format</span>(FPEDATS)]</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate unique analysts each year</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>NumberAnalyst <span class="ot">&lt;-</span> NFLX1[, .(<span class="at">NumAnalysts =</span> <span class="fu">uniqueN</span>(ANALYS)), by <span class="ot">=</span> YEAR]</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print NumberAnalyst object</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(NumberAnalyst)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        YEAR NumAnalysts
 1: 20021231           5
 2: 20031231           9
 3: 20041231          19
 4: 20051231          17
 5: 20061231          20
 6: 20071231          20
 7: 20081231          20
 8: 20091231          33
 9: 20101231          37
10: 20111231          40
11: 20121231          38
12: 20131231          42
13: 20141231          45
14: 20151231          47
15: 20161231          46
16: 20171231          48
17: 20181231          56
18: 20191231          46
19: 20201231          49</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate unique brokerage houses each year</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>NumberBrokerage <span class="ot">&lt;-</span> NFLX1[, .(<span class="at">NumBrokerage =</span> <span class="fu">uniqueN</span>(ESTIMATOR)), by <span class="ot">=</span> YEAR]</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print NumberBrokerage object</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(NumberBrokerage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        YEAR NumBrokerage
 1: 20021231            5
 2: 20031231            8
 3: 20041231           18
 4: 20051231           17
 5: 20061231           19
 6: 20071231           18
 7: 20081231           21
 8: 20091231           32
 9: 20101231           38
10: 20111231           35
11: 20121231           36
12: 20131231           43
13: 20141231           40
14: 20151231           46
15: 20161231           45
16: 20171231           49
17: 20181231           54
18: 20191231           43
19: 20201231           44</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Task 3: Get the most recent forecast in each year
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>It is quite possible that an analyst makes multiple forecasts throughout the year for the same fiscal period. Remove observations from <strong>NFLX1</strong> if an analyst has multiple predictions for the same year and keep the last one (the most recent forecast for each year). Name your new dataset as <strong>NFLX2.</strong> This step is crucial for successful execution of the following tasks. Print the dimension of <code>NFLX2</code>.</p></li>
<li><p>Check your work: If your <code>NFLX2</code> dataset has 641 rows and 14 columns, then you are on the right track. If not, please seek help!</p></li>
</ul>
</div>
</div>
</section>
<section id="your-code-for-task-3" class="level2">
<h2 class="anchored" data-anchor-id="your-code-for-task-3">Your code for Task 3</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Task 3: Get the most recent forecast in each year</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Get most recent forecasts</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>NFLX2 <span class="ot">&lt;-</span> NFLX1 <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(ANALYS, YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(REVDATS <span class="sc">==</span> <span class="fu">max</span>(REVDATS)) <span class="sc">%&gt;%</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>()</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Get dimensions</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(NFLX2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 641  14</code></pre>
</div>
</div>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Task 4: Calculate past accuracy
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Create a copy of <code>NFLX2</code> and call it <code>NFLX3</code></p></li>
<li><p>For every year within the dataset <code>NFLX3</code>, compute the forecasting performance of each analyst for the current year and store the results in a new column labeled <code>accuracy</code>. In the calculation of forecast performance, you can use the VALUE-ACTUAL as the forecast accuracy measure.</p></li>
<li><p>For each year in the <code>NFLX3</code> dataset, compute the forecasting performance of each analyst from the <strong>previous year</strong> and store the results in a new column called <code>past_accuracy</code></p></li>
<li><p>As an example, consider the year 2006, where analyst 1047, employed at brokerage house 464, provided an estimated end-of-period EPS of 0.0929 (VALUE). However, the actual EPS for that year turned out to be 0.1014 (ACTUAL), resulting in a forecasting error of -0.0085. Consequently, in the subsequent year, 2007, the past_accuracy metric for analyst 1047 would reflect this error by taking the value of -0.0085 (VALUE-ACTUAL).</p></li>
<li><p>This action will create some missing values and this is perfectly fine.</p></li>
<li><p>If your code produces 144 NAs, then you are on the right track.</p></li>
<li><p>Note that we are creating copies of the original dataset at each step to facilitate error detection in case any mistakes occur during the process.</p></li>
</ul>
</div>
</div>
</section>
</section>
<section id="your-code-for-task-4" class="level2">
<h2 class="anchored" data-anchor-id="your-code-for-task-4">Your code for Task 4</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create copy</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>NFLX3 <span class="ot">&lt;-</span> NFLX2</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate accuracy</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>NFLX3 <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, ANALYS) <span class="sc">%&gt;%</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">accuracy =</span> VALUE <span class="sc">-</span> ACTUAL) <span class="sc">%&gt;%</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ANALYS) <span class="sc">%&gt;%</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">past_accuracy =</span> <span class="fu">lag</span>(accuracy))</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Check NAs</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(NFLX3<span class="sc">$</span>past_accuracy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 144</code></pre>
</div>
</div>
<section id="section-1" class="level3">
<h3 class="anchored" data-anchor-id="section-1"></h3>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Task 5: Forecast Horizon
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>The longer the forecast horizon, the higher the uncertainty associated with EPS forecasts. To control for this fact, create a new column in <strong>NFLX3</strong> called <strong>horizon</strong> that captures the forecast horizon (ANNDATS_ACT- ANNDATS) for <strong>each analyst</strong>.</p></li>
<li><p>We anticipate observing a negative correlation between <code>accuracy</code> and <code>horizon</code>. Typically, as the forecast horizon increases, the accuracy tends to decrease, and vice versa. However, in our dataset, there is an exception where we find a positive correlation between <code>accuracy</code> and <code>horizon</code> for one specific year. Write an R code to identify and determine which year exhibits this positive correlation.</p></li>
<li><p><strong>Need Written Response in this callout:</strong> Enter the year in here.</p>
<p><strong><em>2018-11-17 with a correlation value of 0.24300105</em></strong></p></li>
</ul>
</div>
</div>
</section>
</section>
<section id="your-code-for-task-5" class="level2">
<h2 class="anchored" data-anchor-id="your-code-for-task-5">Your code for Task 5</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Task 5: Forecast Horizon</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate horizon</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>NFLX3 <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">horizon =</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(ANNDATS_ACT, ANNDATS, <span class="at">units =</span> <span class="st">"days"</span>)))</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlation</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>correlation_by_year <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(YEAR) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">correlation =</span> <span class="fu">cor</span>(accuracy, horizon, <span class="at">use =</span> <span class="st">"complete.obs"</span>))</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert YEAR</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>correlation_by_year<span class="sc">$</span>YEAR <span class="ot">&lt;-</span> <span class="fu">format</span>(<span class="fu">as.POSIXlt</span>(correlation_by_year<span class="sc">$</span>YEAR, <span class="at">format =</span> <span class="st">"%Y"</span>), <span class="st">"%Y-%m-%d %H:%M:%S"</span>)</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Find positive correlation</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>positive_corr_year <span class="ot">&lt;-</span> correlation_by_year <span class="sc">%&gt;%</span> <span class="fu">filter</span>(correlation <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(correlation))</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Print positive correlation year and correlation value</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(positive_corr_year<span class="sc">$</span>YEAR, positive_corr_year<span class="sc">$</span>correlation, <span class="at">sep =</span> <span class="st">" "</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2018-12-06 00:00:00 0.243001051264513" 
[2] "2011-12-06 00:00:00 0.226647459261001" 
[3] "2012-12-06 00:00:00 0.0653612459718447"
[4] "2015-12-06 00:00:00 0.0558201596685652"
[5] "2013-12-06 00:00:00 0.0213974532265298"</code></pre>
</div>
</div>
<section id="section-2" class="level3">
<h3 class="anchored" data-anchor-id="section-2"></h3>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Table 6: Experience
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>We assume that if an analyst is monitoring a company for a long period of time, he/she is expected to make more informed predictions. Create a new column in NFLX3 called <strong>experience</strong> that counts the cumulative number of years the analyst monitor (have predictions) the company. Print the summary of experience column.</p></li>
<li><p><strong>Hint:</strong> Try to use cumsum() function in R.</p></li>
<li><p><strong>Need Written Response in this callout:</strong> Which analyst (s) has the highest number of <strong>experience</strong> in <strong>NFLX3</strong> dataset and for how long do they monitor the NFLX ticker?</p></li>
</ul>
<p><strong><em><code>Two unique analyst with the following identifiers 72088 and 77748 had an hardcore experience of 17 years observing the NTFLX stock and making predictions based on the data provided.</code></em></strong></p>
</div>
</div>
</section>
</section>
<section id="your-code-for-task-6" class="level2">
<h2 class="anchored" data-anchor-id="your-code-for-task-6">Your code for Task 6</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Task 6: Experience</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate cumulative experience</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>NFLX3 <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ANALYS) <span class="sc">%&gt;%</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">experience =</span> <span class="fu">cumsum</span>(<span class="sc">!</span><span class="fu">duplicated</span>(YEAR)))</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Find analyst(s) with the highest experience</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>max_experience <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ANALYS) <span class="sc">%&gt;%</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">experience =</span> <span class="fu">max</span>(experience)) <span class="sc">%&gt;%</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(experience <span class="sc">==</span> <span class="fu">max</span>(experience)) <span class="sc">%&gt;%</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(experience))</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary of the experience column</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NFLX3<span class="sc">$</span>experience)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   2.000   3.000   4.192   6.000  17.000 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print analyst(s) with the highest experience</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(max_experience)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  ANALYS experience
   &lt;int&gt;      &lt;int&gt;
1  72088         17
2  77748         17</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define custom color palette</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>custom_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#66c2a5"</span>, <span class="st">"#fc8d62"</span>, <span class="st">"#8da0cb"</span>, <span class="st">"#e78ac3"</span>, <span class="st">"#a6d854"</span>, <span class="st">"#ffd92f"</span>, <span class="st">"#e5c494"</span>, <span class="st">"#b3b3b3"</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualization with custom colors</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> max_experience, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(ANALYS, <span class="sc">-</span>experience), <span class="at">y =</span> experience, <span class="at">fill =</span> <span class="fu">reorder</span>(ANALYS, <span class="sc">-</span>experience))) <span class="sc">+</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Analyst"</span>, <span class="at">y =</span> <span class="st">"Cumulative Experience"</span>) <span class="sc">+</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> custom_colors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="section-3" class="level3">
<h3 class="anchored" data-anchor-id="section-3"></h3>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Task 7: Size
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>If a brokerage house has multiple analysts providing predictions for the same company, it may indicate a greater allocation of resources for company analysis. To capture this, create a new column in the <code>NFLX3</code> dataset called <code>size</code> that calculates the total count of <strong>unique</strong> analysts employed <strong>per year</strong> by <strong>each</strong> brokerage house (ESTIMATOR)</p></li>
<li><p><strong>Need Written Response in this callout:</strong> Print the frequencies for <strong>size</strong> variable. What does this frequency table reveal about the distribution of the number of analysts hired by brokerage houses in this dataset?</p></li>
</ul>
<p><strong><em><code>We concluded that the number of analysts increase the frequency of hiring reduces exponentially. This indicates that with time the brokerage firm decided to hire an experience analyst per season to maximize productivity.</code></em></strong></p>
</div>
</div>
</section>
</section>
<section id="your-code-for-task-7" class="level2">
<h2 class="anchored" data-anchor-id="your-code-for-task-7">Your code for Task 7</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># Task 7: Size</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate analysts per year</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>NFLX3 <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, ESTIMATOR) <span class="sc">%&gt;%</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">size =</span> <span class="fu">n_distinct</span>(ANALYS))</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print frequencies</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>size_freq <span class="ot">&lt;-</span> <span class="fu">table</span>(NFLX3<span class="sc">$</span>size)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(size_freq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3 
560  72   9 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create frequency table</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>size_table <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(size_freq)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(size_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Analysts"</span>, <span class="st">"Frequency"</span>)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort by frequency</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>size_table <span class="ot">&lt;-</span> size_table[<span class="fu">order</span>(<span class="sc">-</span>size_table<span class="sc">$</span>Frequency), ]</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print sorted table using kableExtra</span></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>size_table <span class="sc">%&gt;%</span></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="st">"html"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Analysts</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">560</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">72</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">9</td>
</tr>
</tbody>
</table>


</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NFLX3<span class="sc">$</span>size)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1.00    1.00    1.00    1.14    1.00    3.00 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize results with different colors</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(size_table<span class="sc">$</span>Frequency, <span class="at">names.arg =</span> size_table<span class="sc">$</span>Analysts,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Analysts"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Analysts by Brokerage"</span>,</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"skyblue"</span>, <span class="st">"salmon"</span>, <span class="st">"lightgreen"</span>), <span class="at">border =</span> <span class="st">"black"</span>,</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">las =</span> <span class="dv">1</span>, <span class="at">cex.names =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="section-4" class="level3">
<h3 class="anchored" data-anchor-id="section-4"></h3>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Task 8: Prediction 1
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>In the year 2020, NETFLIX reported an actual earnings per share (EPS) of $6.08. To predict this EPS value based on historical data, we will employ a linear regression model using the dataset <code>NFLX3</code> up until the year 2019. In this model, the target variable will be <code>ACTUAL</code> and the predictor variables will include <code>VALUE</code> and <code>past_accuracy</code>. C.all your model as <code>model1.</code></p></li>
<li><p><strong>Need Written Response in this callout:</strong> Using the linear regression model ‘model1,’ which has been trained on historical data up to the year 2019, what is the forecasted EPS (Earnings Per Share) for the year 2020? Please provide a brief explanation of the method you employed to make this prediction. If you encountered any challenges or were unable to make the calculation, briefly describe the specific issues you encountered.</p></li>
</ul>
<p><strong><em>Utilizing the linear regression model ‘model1’ trained on historical data until 2019, we can predict the Earnings Per Share (EPS) for 2020. The process involves assessing the model’s goodness of fit, measured by the R-squared value. If the R-squared value surpasses 0.5, indicating a strong fit, the code calculates the mean of the ‘past_accuracy’ variable. When the fit is satisfactory, the model generates a forecast for the future period. This involves creating a new dataset with appropriate values for independent variables (VALUE and past_accuracy) and utilizing the ‘predict’ function to estimate the EPS. Conversely, if the R-squared value falls below the threshold, a warning message alerts that the model might not accurately predict future EPS. Addressing specific challenges related to data configuration or model training is essential to ensure the forecast’s accuracy. This method enables accurate predictions under favorable model fit conditions, ensuring reliable forecasting outcomes.</em></strong></p>
</div>
</div>
</section>
</section>
<section id="your-code-for-task-8" class="level2">
<h2 class="anchored" data-anchor-id="your-code-for-task-8">Your code for Task 8</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean past_accuracy</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>mean_past_accuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(NFLX3<span class="sc">$</span>past_accuracy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create linear regression model</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ACTUAL <span class="sc">~</span> VALUE <span class="sc">+</span> past_accuracy, <span class="at">data =</span> NFLX3)</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Get R-squared value</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>r_squared <span class="ot">&lt;-</span> <span class="fu">summary</span>(model1)<span class="sc">$</span>r.squared</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Check R-squared</span></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (r_squared <span class="sc">&gt;</span> <span class="fl">0.5</span>) {</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create new data frame for future period</span></span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a>  new_data_future <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">VALUE =</span> <span class="fl">6.08</span>,</span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">past_accuracy =</span> mean_past_accuracy</span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb55-19"><a href="#cb55-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-20"><a href="#cb55-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Predict EPS for future</span></span>
<span id="cb55-21"><a href="#cb55-21" aria-hidden="true" tabindex="-1"></a>  predicted_eps_future <span class="ot">&lt;-</span> <span class="fu">predict</span>(model1, <span class="at">newdata =</span> new_data_future)</span>
<span id="cb55-22"><a href="#cb55-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-23"><a href="#cb55-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Print forecasted EPS</span></span>
<span id="cb55-24"><a href="#cb55-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Forecasted EPS: $"</span>, <span class="fu">round</span>(predicted_eps_future, <span class="dv">2</span>))</span>
<span id="cb55-25"><a href="#cb55-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-26"><a href="#cb55-26" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb55-27"><a href="#cb55-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-28"><a href="#cb55-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Print warning</span></span>
<span id="cb55-29"><a href="#cb55-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Low R-squared value."</span>)</span>
<span id="cb55-30"><a href="#cb55-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-31"><a href="#cb55-31" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Forecasted EPS: $ 6.3</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print mean past_accuracy</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Mean past_accuracy: "</span>, <span class="fu">round</span>(mean_past_accuracy, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Mean past_accuracy:  -0.09</code></pre>
</div>
</div>
<section id="section-5" class="level3">
<h3 class="anchored" data-anchor-id="section-5"></h3>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Task 9: Prediction 2
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>As an alternative approach, instead of modeling the ‘ACTUAL’ value, we can obtain the mean and median forecasts for the year 2020 as our best estimates of the EPS value for that year.</p></li>
<li><p><strong>Need Written Response in this callout:</strong> Please calculate these forecasts and then compare them with the results from the previous task. Finally, provide your insights and comments based on your findings.</p></li>
</ul>
<p><strong><em>In this alternative approach, we calculated both the mean and median forecasts for the year 2020 to estimate the EPS value. The mean forecast stood at approximately $1.24, whereas the median forecast was notably lower, around $0.41. Comparing these outcomes with the linear regression model used earlier, it becomes evident that the model-based forecast offers a more detailed and potentially accurate prediction. However, each method has its distinct advantages and disadvantages. The model-driven forecast considers historical relationships and variables like ‘past_accuracy,’ but its accuracy heavily depends on the quality of the model fit, indicated by the R-squared value. On the contrary, the mean and median forecasts provide straightforward summary statistics but might lack the predictive strength of a well-fitted model. The choice between these methods should be made considering the data quality and the specific context of the analysis.</em></strong></p>
</div>
</div>
</section>
</section>
<section id="your-code-for-task-9" class="level2">
<h2 class="anchored" data-anchor-id="your-code-for-task-9">Your code for Task 9</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean forecast</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>mean_forecast <span class="ot">&lt;-</span> <span class="fu">mean</span>(NFLX3<span class="sc">$</span>VALUE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate median forecast</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>median_forecast <span class="ot">&lt;-</span> <span class="fu">median</span>(NFLX3<span class="sc">$</span>VALUE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print forecasts</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Mean forecast: $"</span>, <span class="fu">round</span>(mean_forecast, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Mean forecast: $ 1.24</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Median forecast: $"</span>, <span class="fu">round</span>(median_forecast, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Median forecast: $ 0.41</code></pre>
</div>
</div>
<section id="section-6" class="level3">
<h3 class="anchored" data-anchor-id="section-6"></h3>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Task 10: Averages
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Generate a new dataset named <code>NFLX4</code> by aggregating data from <code>NFLX3</code> Include the variables <code>size</code>, <code>experience</code>, <code>horizon</code>, <code>accuracy,</code> <code>past_accuracy</code>, and <code>ACTUAL</code> in <code>NFLX4</code>. When calculating the yearly averages for these variables, ignore any missing values (NAs). Present a summary of the <code>NFLX4</code> dataset.</p></li>
<li><p><strong>Need Written Response in this callout:</strong> Subsequently, employ correlation analysis or exploratory data analysis to get insights into the relationships between these variables and ‘ACTUAL,’ if such relationships exist.</p></li>
</ul>
<p><strong><em><code>Following an in-depth analysis of the NFLX4 dataset, significant patterns concerning the relationship between variables and 'ACTUAL' earnings per share have been uncovered. The correlation analysis indicated that 'ACTUAL' is positively linked with 'size' (0.18) and 'experience' (0.69), implying that larger and more experienced analyst groups tend to deliver more precise forecasts for 'ACTUAL'. Conversely, 'ACTUAL' exhibits negative correlations with 'horizon' (-0.63) and 'past_accuracy' (-0.80), indicating that analysts with longer forecasting periods and higher past accuracy often produce less accurate predictions for 'ACTUAL'. Visual representations through scatter plots reinforce these findings, such as the trend showing enhanced accuracy with an increase in the number of analysts in the 'ACTUAL' versus 'size' plot. These insights shed light on the factors influencing earnings per share forecasts, underscoring the importance of analyst group size and experience while emphasizing the potential drawbacks of longer forecasting horizons and overly accurate track records, crucial knowledge for financial analysts, investors, and decision-makers.</code></em></strong></p>
</div>
</div>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate and calculate averages</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>NFLX4 <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fu">mean</span>(size, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">experience =</span> <span class="fu">mean</span>(experience, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">horizon =</span> <span class="fu">mean</span>(horizon, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">accuracy =</span> <span class="fu">mean</span>(accuracy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">past_accuracy =</span> <span class="fu">mean</span>(past_accuracy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">ACTUAL =</span> <span class="fu">mean</span>(ACTUAL, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of NFLX4 dataset</span></span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NFLX4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     YEAR                size         experience       horizon       
 Length:19          Min.   :1.000   Min.   :1.000   Min.   :0.06284  
 Class :character   1st Qu.:1.074   1st Qu.:2.664   1st Qu.:0.08547  
 Mode  :character   Median :1.105   Median :3.400   Median :0.09289  
                    Mean   :1.132   Mean   :3.611   Mean   :0.09004  
                    3rd Qu.:1.202   3rd Qu.:4.869   3rd Qu.:0.09512  
                    Max.   :1.300   Max.   :6.061   Max.   :0.10656  
                                                                     
    accuracy         past_accuracy           ACTUAL       
 Min.   :-0.822085   Min.   :-0.798219   Min.   :-0.0050  
 1st Qu.:-0.019087   1st Qu.:-0.028736   1st Qu.: 0.0914  
 Median :-0.015035   Median :-0.013423   Median : 0.2643  
 Mean   :-0.048310   Mean   :-0.060652   Mean   : 0.9248  
 3rd Qu.:-0.005415   3rd Qu.:-0.009260   3rd Qu.: 0.5678  
 Max.   : 0.121449   Max.   :-0.001547   Max.   : 6.0800  
                     NA's   :1                            </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a correlation matrix</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>correlation_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(NFLX4[, <span class="fu">c</span>(<span class="st">"size"</span>, <span class="st">"experience"</span>, <span class="st">"horizon"</span>, <span class="st">"accuracy"</span>, <span class="st">"past_accuracy"</span>, <span class="st">"ACTUAL"</span>)], <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Custom color palette</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>color_palette <span class="ot">&lt;-</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">"#FFFFFF"</span>, <span class="st">"#67a9cf"</span>, <span class="st">"#ef8a62"</span>, <span class="st">"#b2182b"</span>))(<span class="dv">100</span>)</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a correlation plot with enhanced customization</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(</span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>  correlation_matrix,</span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"color"</span>,</span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> color_palette,</span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"upper"</span>,</span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">order =</span> <span class="st">"original"</span>,</span>
<span id="cb65-15"><a href="#cb65-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">tl.cex =</span> <span class="fl">0.7</span>,  <span class="co"># Adjust the size of text labels</span></span>
<span id="cb65-16"><a href="#cb65-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">cl.cex =</span> <span class="fl">0.8</span>,  <span class="co"># Adjust the size of correlation coefficients</span></span>
<span id="cb65-17"><a href="#cb65-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">diag =</span> <span class="cn">FALSE</span>,</span>
<span id="cb65-18"><a href="#cb65-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">number.cex =</span> <span class="fl">0.8</span></span>
<span id="cb65-19"><a href="#cb65-19" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print correlation matrix</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(correlation_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                     size  experience    horizon    accuracy past_accuracy
size           1.00000000  0.07451284 -0.1317823 -0.04537307    -0.1810330
experience     0.07451284  1.00000000 -0.4844637 -0.25882136    -0.4620906
horizon       -0.13178225 -0.48446371  1.0000000  0.22264895     0.4979377
accuracy      -0.04537307 -0.25882136  0.2226489  1.00000000    -0.1604379
past_accuracy -0.18103301 -0.46209061  0.4979377 -0.16043792     1.0000000
ACTUAL         0.18223220  0.68707354 -0.6346966 -0.31928984    -0.7958850
                  ACTUAL
size           0.1822322
experience     0.6870735
horizon       -0.6346966
accuracy      -0.3192898
past_accuracy -0.7958850
ACTUAL         1.0000000</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(NFLX4, <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">"size"</span>, <span class="st">"experience"</span>, <span class="st">"horizon"</span>, <span class="st">"accuracy"</span>, <span class="st">"past_accuracy"</span>, <span class="st">"ACTUAL"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in ggally_statistic(data = data, mapping = mapping, na.rm = na.rm, :
Removing 1 row that contained a missing value

Warning in ggally_statistic(data = data, mapping = mapping, na.rm = na.rm, :
Removing 1 row that contained a missing value

Warning in ggally_statistic(data = data, mapping = mapping, na.rm = na.rm, :
Removing 1 row that contained a missing value

Warning in ggally_statistic(data = data, mapping = mapping, na.rm = na.rm, :
Removing 1 row that contained a missing value</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing missing values (`geom_point()`).
Removed 1 rows containing missing values (`geom_point()`).
Removed 1 rows containing missing values (`geom_point()`).
Removed 1 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in ggally_statistic(data = data, mapping = mapping, na.rm = na.rm, :
Removing 1 row that contained a missing value</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(NFLX4, <span class="fu">aes</span>(<span class="at">x =</span> size)) <span class="sc">+</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"#009999"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">bins =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Distribution of Size"</span>) <span class="sc">+</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Size"</span>) <span class="sc">+</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid" width="672"></p>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(NFLX4, <span class="fu">aes</span>(<span class="at">y =</span> size)) <span class="sc">+</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"#009999"</span>) <span class="sc">+</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Boxplot of Size"</span>) <span class="sc">+</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Size"</span>) <span class="sc">+</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid" width="672"></p>
</div>
</div>


<!-- -->

</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb76" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Mini Group Project 1"</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Surya Vardham"</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a><span class="an">editor:</span><span class="co"> visual</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a><span class="fu"># Business Problem</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>In this group project, you will work with analysts' forecast data of earning per share (EPS) provided by Wharton Research Data Services (WRDS). Institutional Brokers' Estimate System (I/B/E/S) provides historical data on certain financial indicators collected from thousands of individual analysts working in more than 3,000 broker houses.</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**TICKER:** A unique identifier assigned to each security. In this group project, you will only model "NFLX" ticker.</span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**CNAME:** Company name</span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**ACTDATS:** The Activation date: It is the date when the analyst forecast became effective within the IBES database.</span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**ESTIMATOR:** Sellside institution (mostly broker house). It is just the broker.</span>
<span id="cb76-18"><a href="#cb76-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-19"><a href="#cb76-19" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**ANALYS:** The person who makes the forecast and work for sellside institution. Estimators and analysts are represented by codes to hide their real names.</span>
<span id="cb76-20"><a href="#cb76-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-21"><a href="#cb76-21" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**FPI:** Forecast Period Indicator: The forecasting period. 6: Next Fiscal Quarter 1: Next Fiscal Year</span>
<span id="cb76-22"><a href="#cb76-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-23"><a href="#cb76-23" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**MEASURE**: The variable being estimated. We have data for earning per share (EPS)</span>
<span id="cb76-24"><a href="#cb76-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-25"><a href="#cb76-25" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**VALUE:** The forecasted value of EPS</span>
<span id="cb76-26"><a href="#cb76-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-27"><a href="#cb76-27" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**FPEDATS**: The Forecast Period End Date: It is the ending date of the fiscal period to which the estimate applies. For the majority of companies, the FPEDATS date is December 31st of that year.</span>
<span id="cb76-28"><a href="#cb76-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-29"><a href="#cb76-29" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**REVDATS:** The Review Date: It is the most recent date on which IBES called the analyst and verified that particular estimate as still valid for that analyst. If an analyst confirms that a previous estimate is still valid, the original database record for that estimate is retained and only the REVDATS variable is updated. If an analyst changes their estimate for a given company, a new record is entered in the database with a new ANNDATS. The old record of the analyst (containing the previous estimate) is retained in the database.</span>
<span id="cb76-30"><a href="#cb76-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-31"><a href="#cb76-31" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**REVTIMS**: Time-stamp of REVDATS</span>
<span id="cb76-32"><a href="#cb76-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-33"><a href="#cb76-33" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**ANNDATS**: The Announce date: It is the date on which the analyst first made that particular estimate.</span>
<span id="cb76-34"><a href="#cb76-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-35"><a href="#cb76-35" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**ANNTIMS**: Time-stamp of ANNDATS</span>
<span id="cb76-36"><a href="#cb76-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-37"><a href="#cb76-37" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**ACTUAL**: The realized EPS, the true EPS value.</span>
<span id="cb76-38"><a href="#cb76-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-39"><a href="#cb76-39" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**ANNDATS_ACT**: The Announced date of Actual EPS: The actual EPS value is announced by the company at this date.</span>
<span id="cb76-40"><a href="#cb76-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-41"><a href="#cb76-41" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**ANNTIMS_ACT**: The time-stamp of ANNDATS_ACT</span>
<span id="cb76-42"><a href="#cb76-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-43"><a href="#cb76-43" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE, warning=FALSE}</span></span>
<span id="cb76-44"><a href="#cb76-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required libraries</span></span>
<span id="cb76-45"><a href="#cb76-45" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"data.table"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb76-46"><a href="#cb76-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"data.table"</span>)</span>
<span id="cb76-47"><a href="#cb76-47" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb76-48"><a href="#cb76-48" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb76-49"><a href="#cb76-49" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb76-50"><a href="#cb76-50" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb76-51"><a href="#cb76-51" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb76-52"><a href="#cb76-52" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb76-53"><a href="#cb76-53" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb76-54"><a href="#cb76-54" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb76-55"><a href="#cb76-55" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb76-56"><a href="#cb76-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-57"><a href="#cb76-57" aria-hidden="true" tabindex="-1"></a><span class="co"># Read CSV file</span></span>
<span id="cb76-58"><a href="#cb76-58" aria-hidden="true" tabindex="-1"></a>NFLX <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:/Users/HP/Downloads/NFLX.csv"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb76-59"><a href="#cb76-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-60"><a href="#cb76-60" aria-hidden="true" tabindex="-1"></a><span class="co"># Display column names</span></span>
<span id="cb76-61"><a href="#cb76-61" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(NFLX)</span>
<span id="cb76-62"><a href="#cb76-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-63"><a href="#cb76-63" aria-hidden="true" tabindex="-1"></a><span class="co"># View first rows</span></span>
<span id="cb76-64"><a href="#cb76-64" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(NFLX)</span>
<span id="cb76-65"><a href="#cb76-65" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-66"><a href="#cb76-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-67"><a href="#cb76-67" aria-hidden="true" tabindex="-1"></a><span class="fu">## How to read the data</span></span>
<span id="cb76-68"><a href="#cb76-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-69"><a href="#cb76-69" aria-hidden="true" tabindex="-1"></a>**The first row in NFLX data set**: On 09‐Aug-2002 (ANNDATS), analyst 6749 (ANALYS) at Estimator 1872 (ESTIMATOR) predicts that the EPS (MEASURE) for NETFLIX INC. (CNAME) with a ticker of NFLX (TICKER) with forecast period ending 30‐Sep-2002 (FPEDATS) is -\$0.0086 (VALUE). This estimates was entered into the database on 12‐Aug-2002 (ACTDATS). On 17-Oct-2002 (ANNDATS_ACT), NETFLIX INC. announced an actual EPS of \$7e-04 (\$0.0007) (ACTUAL) for this quarter (FPI=6).</span>
<span id="cb76-70"><a href="#cb76-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-71"><a href="#cb76-71" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb76-72"><a href="#cb76-72" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(NFLX,<span class="at">n=</span><span class="dv">1</span>)</span>
<span id="cb76-73"><a href="#cb76-73" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-74"><a href="#cb76-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-75"><a href="#cb76-75" aria-hidden="true" tabindex="-1"></a><span class="fu">## Your Turn:</span></span>
<span id="cb76-76"><a href="#cb76-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-77"><a href="#cb76-77" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple"}</span>
<span id="cb76-78"><a href="#cb76-78" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task 1A: Calculate Missingness</span></span>
<span id="cb76-79"><a href="#cb76-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-80"><a href="#cb76-80" aria-hidden="true" tabindex="-1"></a>Check to see the missing values in NFLX dataset and calculate the percent missing for each variable in <span class="in">`NFLX`</span> and list your findings in R object called <span class="in">`NFLX_missingness`</span>. <span class="in">`NFLX_missingness`</span> is a dataframe with two columns: The first column, <span class="in">`Variable`</span>, stores the variable names and the second column, <span class="in">`Missingness`</span> shows the percent missing in percentage points with two decimal points.</span>
<span id="cb76-81"><a href="#cb76-81" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-82"><a href="#cb76-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-83"><a href="#cb76-83" aria-hidden="true" tabindex="-1"></a><span class="fu">## Your code for Task 1A</span></span>
<span id="cb76-84"><a href="#cb76-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-85"><a href="#cb76-85" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb76-86"><a href="#cb76-86" aria-hidden="true" tabindex="-1"></a><span class="co"># Read CSV file</span></span>
<span id="cb76-87"><a href="#cb76-87" aria-hidden="true" tabindex="-1"></a>NFLX <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"C:/Users/HP/Downloads/NFLX.csv"</span>)</span>
<span id="cb76-88"><a href="#cb76-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-89"><a href="#cb76-89" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate missingness manually</span></span>
<span id="cb76-90"><a href="#cb76-90" aria-hidden="true" tabindex="-1"></a>missingness_percentages <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(<span class="fu">is.na</span>(NFLX)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb76-91"><a href="#cb76-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-92"><a href="#cb76-92" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame with Variable names and MissingPercentage values</span></span>
<span id="cb76-93"><a href="#cb76-93" aria-hidden="true" tabindex="-1"></a>missing_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Variable =</span> <span class="fu">names</span>(missingness_percentages), <span class="at">MissingPercentage =</span> missingness_percentages)</span>
<span id="cb76-94"><a href="#cb76-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-95"><a href="#cb76-95" aria-hidden="true" tabindex="-1"></a><span class="co"># Print missingness percentages</span></span>
<span id="cb76-96"><a href="#cb76-96" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Missing Values Percentage by Variable"</span>)</span>
<span id="cb76-97"><a href="#cb76-97" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_data)</span>
<span id="cb76-98"><a href="#cb76-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-99"><a href="#cb76-99" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize missing values with custom color</span></span>
<span id="cb76-100"><a href="#cb76-100" aria-hidden="true" tabindex="-1"></a>missingness_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb76-101"><a href="#cb76-101" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Variable, <span class="sc">-</span>MissingPercentage), <span class="at">y =</span> MissingPercentage)) <span class="sc">+</span></span>
<span id="cb76-102"><a href="#cb76-102" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"#66c2a5"</span>) <span class="sc">+</span>  <span class="co"># Custom color: greenish</span></span>
<span id="cb76-103"><a href="#cb76-103" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Missing Values Percentage by Variable"</span>, </span>
<span id="cb76-104"><a href="#cb76-104" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Variable"</span>, <span class="at">y =</span> <span class="st">"Missing Percentage"</span>) <span class="sc">+</span></span>
<span id="cb76-105"><a href="#cb76-105" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb76-106"><a href="#cb76-106" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb76-107"><a href="#cb76-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-108"><a href="#cb76-108" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate and display missing values plot</span></span>
<span id="cb76-109"><a href="#cb76-109" aria-hidden="true" tabindex="-1"></a><span class="fu">missingness_plot</span>(missing_data)</span>
<span id="cb76-110"><a href="#cb76-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-111"><a href="#cb76-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-112"><a href="#cb76-112" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple"}</span>
<span id="cb76-113"><a href="#cb76-113" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task 1B: Data Manipulation</span></span>
<span id="cb76-114"><a href="#cb76-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-115"><a href="#cb76-115" aria-hidden="true" tabindex="-1"></a>Conduct the following data manipulations on <span class="in">`NFLX`</span>:</span>
<span id="cb76-116"><a href="#cb76-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-117"><a href="#cb76-117" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Drop rows from the data set when a variable has a missing value</span>
<span id="cb76-118"><a href="#cb76-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-119"><a href="#cb76-119" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Drop rows from the data set the quarterly forecasts (drop FPI=6)</span>
<span id="cb76-120"><a href="#cb76-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-121"><a href="#cb76-121" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Declare TICKER, CNAME, ESTIMATOR , ANALYS, FPI , and MEASURE variables as factor</span>
<span id="cb76-122"><a href="#cb76-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-123"><a href="#cb76-123" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Declare ACTDATS, FPEDATS , ANNDATS, REVDATS, ANNDATS_ACT as time variable.</span>
<span id="cb76-124"><a href="#cb76-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-125"><a href="#cb76-125" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Drop ANNTIMS_ACT, ANNTIMS , and REVTIMS</span>
<span id="cb76-126"><a href="#cb76-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-127"><a href="#cb76-127" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Create a new column named YEAR that captures the year in FPEDATS</span>
<span id="cb76-128"><a href="#cb76-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-129"><a href="#cb76-129" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Name your reduced dataset as <span class="in">`NFLX1`</span></span>
<span id="cb76-130"><a href="#cb76-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-131"><a href="#cb76-131" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Print out data structure and the summary of NFLX1</span>
<span id="cb76-132"><a href="#cb76-132" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-133"><a href="#cb76-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-134"><a href="#cb76-134" aria-hidden="true" tabindex="-1"></a><span class="fu">## Your code for Task 1B</span></span>
<span id="cb76-135"><a href="#cb76-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-136"><a href="#cb76-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb76-137"><a href="#cb76-137" aria-hidden="true" tabindex="-1"></a><span class="co"># Copy NFLX to NFLX1 without assigning data types</span></span>
<span id="cb76-138"><a href="#cb76-138" aria-hidden="true" tabindex="-1"></a>NFLX1 <span class="ot">&lt;-</span> NFLX</span>
<span id="cb76-139"><a href="#cb76-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-140"><a href="#cb76-140" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows from the data set when a variable has a missing value</span></span>
<span id="cb76-141"><a href="#cb76-141" aria-hidden="true" tabindex="-1"></a>NFLX1 <span class="ot">&lt;-</span> NFLX1 <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>()</span>
<span id="cb76-142"><a href="#cb76-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-143"><a href="#cb76-143" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows from the data set where FPI=6</span></span>
<span id="cb76-144"><a href="#cb76-144" aria-hidden="true" tabindex="-1"></a>NFLX1 <span class="ot">&lt;-</span> NFLX1 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FPI <span class="sc">!=</span> <span class="dv">6</span>)</span>
<span id="cb76-145"><a href="#cb76-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-146"><a href="#cb76-146" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop ANNTIMS_ACT, ANNTIMS, and REVTIMS</span></span>
<span id="cb76-147"><a href="#cb76-147" aria-hidden="true" tabindex="-1"></a>NFLX1 <span class="ot">&lt;-</span> NFLX1 <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>ANNTIMS_ACT, <span class="sc">-</span>ANNTIMS, <span class="sc">-</span>REVTIMS)</span>
<span id="cb76-148"><a href="#cb76-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-149"><a href="#cb76-149" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column named YEAR that is an exact copy of the data in FPEDATS</span></span>
<span id="cb76-150"><a href="#cb76-150" aria-hidden="true" tabindex="-1"></a>NFLX1 <span class="ot">&lt;-</span> NFLX1 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">YEAR =</span> FPEDATS)</span>
<span id="cb76-151"><a href="#cb76-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-152"><a href="#cb76-152" aria-hidden="true" tabindex="-1"></a><span class="co"># Print out data structure and the summary of NFLX1</span></span>
<span id="cb76-153"><a href="#cb76-153" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(NFLX1)</span>
<span id="cb76-154"><a href="#cb76-154" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NFLX1)</span>
<span id="cb76-155"><a href="#cb76-155" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-156"><a href="#cb76-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-157"><a href="#cb76-157" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple"}</span>
<span id="cb76-158"><a href="#cb76-158" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task 2: Calculate Number of Analysts and Brokerage Houses</span></span>
<span id="cb76-159"><a href="#cb76-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-160"><a href="#cb76-160" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Calculate the total number of **unique** analysts in **NFLX1** dataset that provide forecasts **each year** and name your R object as **NumberAnalyst**</span>
<span id="cb76-161"><a href="#cb76-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-162"><a href="#cb76-162" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Calculate the total number of **unique** brokerage houses (ESTIMATOR) in **NFLX1** dataset that provide forecasts **each year** and name your R object as **NumberBrokerage**</span>
<span id="cb76-163"><a href="#cb76-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-164"><a href="#cb76-164" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Need Written Response in this callout:** In which year(s) we have the highest number of unique analysts providing forecasts for NFLX ticker? In which year(s), we have the highest number of unique brokerage houses providing forecasts for the NFLX ticker.</span>
<span id="cb76-165"><a href="#cb76-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-166"><a href="#cb76-166" aria-hidden="true" tabindex="-1"></a>***`2020 is the year December 31 is the month which had the most unique number of analyst providing forecast for NTFLX.`***</span>
<span id="cb76-167"><a href="#cb76-167" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-168"><a href="#cb76-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-169"><a href="#cb76-169" aria-hidden="true" tabindex="-1"></a><span class="fu">## Your code for Task 2</span></span>
<span id="cb76-170"><a href="#cb76-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-171"><a href="#cb76-171" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb76-172"><a href="#cb76-172" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column named YEAR</span></span>
<span id="cb76-173"><a href="#cb76-173" aria-hidden="true" tabindex="-1"></a>NFLX1[, YEAR <span class="sc">:</span><span class="er">=</span> <span class="fu">format</span>(FPEDATS)]</span>
<span id="cb76-174"><a href="#cb76-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-175"><a href="#cb76-175" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate unique analysts each year</span></span>
<span id="cb76-176"><a href="#cb76-176" aria-hidden="true" tabindex="-1"></a>NumberAnalyst <span class="ot">&lt;-</span> NFLX1[, .(<span class="at">NumAnalysts =</span> <span class="fu">uniqueN</span>(ANALYS)), by <span class="ot">=</span> YEAR]</span>
<span id="cb76-177"><a href="#cb76-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-178"><a href="#cb76-178" aria-hidden="true" tabindex="-1"></a><span class="co"># Print NumberAnalyst object</span></span>
<span id="cb76-179"><a href="#cb76-179" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(NumberAnalyst)</span>
<span id="cb76-180"><a href="#cb76-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-181"><a href="#cb76-181" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate unique brokerage houses each year</span></span>
<span id="cb76-182"><a href="#cb76-182" aria-hidden="true" tabindex="-1"></a>NumberBrokerage <span class="ot">&lt;-</span> NFLX1[, .(<span class="at">NumBrokerage =</span> <span class="fu">uniqueN</span>(ESTIMATOR)), by <span class="ot">=</span> YEAR]</span>
<span id="cb76-183"><a href="#cb76-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-184"><a href="#cb76-184" aria-hidden="true" tabindex="-1"></a><span class="co"># Print NumberBrokerage object</span></span>
<span id="cb76-185"><a href="#cb76-185" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(NumberBrokerage)</span>
<span id="cb76-186"><a href="#cb76-186" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-187"><a href="#cb76-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-188"><a href="#cb76-188" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple"}</span>
<span id="cb76-189"><a href="#cb76-189" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task 3: Get the most recent forecast in each year</span></span>
<span id="cb76-190"><a href="#cb76-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-191"><a href="#cb76-191" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>It is quite possible that an analyst makes multiple forecasts throughout the year for the same fiscal period. Remove observations from **NFLX1** if an analyst has multiple predictions for the same year and keep the last one (the most recent forecast for each year). Name your new dataset as **NFLX2.** This step is crucial for successful execution of the following tasks. Print the dimension of <span class="in">`NFLX2`</span>.</span>
<span id="cb76-192"><a href="#cb76-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-193"><a href="#cb76-193" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Check your work: If your <span class="in">`NFLX2`</span> dataset has 641 rows and 14 columns, then you are on the right track. If not, please seek help!</span>
<span id="cb76-194"><a href="#cb76-194" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-195"><a href="#cb76-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-196"><a href="#cb76-196" aria-hidden="true" tabindex="-1"></a><span class="fu">## Your code for Task 3</span></span>
<span id="cb76-197"><a href="#cb76-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-198"><a href="#cb76-198" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb76-199"><a href="#cb76-199" aria-hidden="true" tabindex="-1"></a><span class="co"># Task 3: Get the most recent forecast in each year</span></span>
<span id="cb76-200"><a href="#cb76-200" aria-hidden="true" tabindex="-1"></a><span class="co"># Get most recent forecasts</span></span>
<span id="cb76-201"><a href="#cb76-201" aria-hidden="true" tabindex="-1"></a>NFLX2 <span class="ot">&lt;-</span> NFLX1 <span class="sc">%&gt;%</span></span>
<span id="cb76-202"><a href="#cb76-202" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(ANALYS, YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb76-203"><a href="#cb76-203" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(REVDATS <span class="sc">==</span> <span class="fu">max</span>(REVDATS)) <span class="sc">%&gt;%</span></span>
<span id="cb76-204"><a href="#cb76-204" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>()</span>
<span id="cb76-205"><a href="#cb76-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-206"><a href="#cb76-206" aria-hidden="true" tabindex="-1"></a><span class="co"># Get dimensions</span></span>
<span id="cb76-207"><a href="#cb76-207" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(NFLX2)</span>
<span id="cb76-208"><a href="#cb76-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-209"><a href="#cb76-209" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-210"><a href="#cb76-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-211"><a href="#cb76-211" aria-hidden="true" tabindex="-1"></a><span class="fu">### </span></span>
<span id="cb76-212"><a href="#cb76-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-213"><a href="#cb76-213" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple"}</span>
<span id="cb76-214"><a href="#cb76-214" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task 4: Calculate past accuracy</span></span>
<span id="cb76-215"><a href="#cb76-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-216"><a href="#cb76-216" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Create a copy of <span class="in">`NFLX2`</span> and call it <span class="in">`NFLX3`</span></span>
<span id="cb76-217"><a href="#cb76-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-218"><a href="#cb76-218" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>For every year within the dataset <span class="in">`NFLX3`</span>, compute the forecasting performance of each analyst for the current year and store the results in a new column labeled <span class="in">`accuracy`</span>. In the calculation of forecast performance, you can use the VALUE-ACTUAL as the forecast accuracy measure.</span>
<span id="cb76-219"><a href="#cb76-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-220"><a href="#cb76-220" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>For each year in the <span class="in">`NFLX3`</span> dataset, compute the forecasting performance of each analyst from the **previous year** and store the results in a new column called <span class="in">`past_accuracy`</span></span>
<span id="cb76-221"><a href="#cb76-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-222"><a href="#cb76-222" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>As an example, consider the year 2006, where analyst 1047, employed at brokerage house 464, provided an estimated end-of-period EPS of 0.0929 (VALUE). However, the actual EPS for that year turned out to be 0.1014 (ACTUAL), resulting in a forecasting error of -0.0085. Consequently, in the subsequent year, 2007, the past_accuracy metric for analyst 1047 would reflect this error by taking the value of -0.0085 (VALUE-ACTUAL).</span>
<span id="cb76-223"><a href="#cb76-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-224"><a href="#cb76-224" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>This action will create some missing values and this is perfectly fine.</span>
<span id="cb76-225"><a href="#cb76-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-226"><a href="#cb76-226" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>If your code produces 144 NAs, then you are on the right track.</span>
<span id="cb76-227"><a href="#cb76-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-228"><a href="#cb76-228" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Note that we are creating copies of the original dataset at each step to facilitate error detection in case any mistakes occur during the process.</span>
<span id="cb76-229"><a href="#cb76-229" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-230"><a href="#cb76-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-231"><a href="#cb76-231" aria-hidden="true" tabindex="-1"></a><span class="fu">## Your code for Task 4</span></span>
<span id="cb76-232"><a href="#cb76-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-233"><a href="#cb76-233" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb76-234"><a href="#cb76-234" aria-hidden="true" tabindex="-1"></a><span class="co"># Create copy</span></span>
<span id="cb76-235"><a href="#cb76-235" aria-hidden="true" tabindex="-1"></a>NFLX3 <span class="ot">&lt;-</span> NFLX2</span>
<span id="cb76-236"><a href="#cb76-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-237"><a href="#cb76-237" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate accuracy</span></span>
<span id="cb76-238"><a href="#cb76-238" aria-hidden="true" tabindex="-1"></a>NFLX3 <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span></span>
<span id="cb76-239"><a href="#cb76-239" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, ANALYS) <span class="sc">%&gt;%</span></span>
<span id="cb76-240"><a href="#cb76-240" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">accuracy =</span> VALUE <span class="sc">-</span> ACTUAL) <span class="sc">%&gt;%</span></span>
<span id="cb76-241"><a href="#cb76-241" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ANALYS) <span class="sc">%&gt;%</span></span>
<span id="cb76-242"><a href="#cb76-242" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb76-243"><a href="#cb76-243" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">past_accuracy =</span> <span class="fu">lag</span>(accuracy))</span>
<span id="cb76-244"><a href="#cb76-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-245"><a href="#cb76-245" aria-hidden="true" tabindex="-1"></a><span class="co"># Check NAs</span></span>
<span id="cb76-246"><a href="#cb76-246" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(NFLX3<span class="sc">$</span>past_accuracy))</span>
<span id="cb76-247"><a href="#cb76-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-248"><a href="#cb76-248" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-249"><a href="#cb76-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-250"><a href="#cb76-250" aria-hidden="true" tabindex="-1"></a><span class="fu">### </span></span>
<span id="cb76-251"><a href="#cb76-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-252"><a href="#cb76-252" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple"}</span>
<span id="cb76-253"><a href="#cb76-253" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task 5: Forecast Horizon</span></span>
<span id="cb76-254"><a href="#cb76-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-255"><a href="#cb76-255" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The longer the forecast horizon, the higher the uncertainty associated with EPS forecasts. To control for this fact, create a new column in **NFLX3** called **horizon** that captures the forecast horizon (ANNDATS_ACT- ANNDATS) for **each analyst**.</span>
<span id="cb76-256"><a href="#cb76-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-257"><a href="#cb76-257" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>We anticipate observing a negative correlation between <span class="in">`accuracy`</span> and <span class="in">`horizon`</span>. Typically, as the forecast horizon increases, the accuracy tends to decrease, and vice versa. However, in our dataset, there is an exception where we find a positive correlation between <span class="in">`accuracy`</span> and <span class="in">`horizon`</span> for one specific year. Write an R code to identify and determine which year exhibits this positive correlation.</span>
<span id="cb76-258"><a href="#cb76-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-259"><a href="#cb76-259" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Need Written Response in this callout:** Enter the year in here.</span>
<span id="cb76-260"><a href="#cb76-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-261"><a href="#cb76-261" aria-hidden="true" tabindex="-1"></a>    ***2018-11-17 with a correlation value of 0.24300105***</span>
<span id="cb76-262"><a href="#cb76-262" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-263"><a href="#cb76-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-264"><a href="#cb76-264" aria-hidden="true" tabindex="-1"></a><span class="fu">## Your code for Task 5</span></span>
<span id="cb76-265"><a href="#cb76-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-266"><a href="#cb76-266" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb76-267"><a href="#cb76-267" aria-hidden="true" tabindex="-1"></a><span class="co"># Task 5: Forecast Horizon</span></span>
<span id="cb76-268"><a href="#cb76-268" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate horizon</span></span>
<span id="cb76-269"><a href="#cb76-269" aria-hidden="true" tabindex="-1"></a>NFLX3 <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">horizon =</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(ANNDATS_ACT, ANNDATS, <span class="at">units =</span> <span class="st">"days"</span>)))</span>
<span id="cb76-270"><a href="#cb76-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-271"><a href="#cb76-271" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlation</span></span>
<span id="cb76-272"><a href="#cb76-272" aria-hidden="true" tabindex="-1"></a>correlation_by_year <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(YEAR) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">correlation =</span> <span class="fu">cor</span>(accuracy, horizon, <span class="at">use =</span> <span class="st">"complete.obs"</span>))</span>
<span id="cb76-273"><a href="#cb76-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-274"><a href="#cb76-274" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert YEAR</span></span>
<span id="cb76-275"><a href="#cb76-275" aria-hidden="true" tabindex="-1"></a>correlation_by_year<span class="sc">$</span>YEAR <span class="ot">&lt;-</span> <span class="fu">format</span>(<span class="fu">as.POSIXlt</span>(correlation_by_year<span class="sc">$</span>YEAR, <span class="at">format =</span> <span class="st">"%Y"</span>), <span class="st">"%Y-%m-%d %H:%M:%S"</span>)</span>
<span id="cb76-276"><a href="#cb76-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-277"><a href="#cb76-277" aria-hidden="true" tabindex="-1"></a><span class="co"># Find positive correlation</span></span>
<span id="cb76-278"><a href="#cb76-278" aria-hidden="true" tabindex="-1"></a>positive_corr_year <span class="ot">&lt;-</span> correlation_by_year <span class="sc">%&gt;%</span> <span class="fu">filter</span>(correlation <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(correlation))</span>
<span id="cb76-279"><a href="#cb76-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-280"><a href="#cb76-280" aria-hidden="true" tabindex="-1"></a><span class="co"># Print positive correlation year and correlation value</span></span>
<span id="cb76-281"><a href="#cb76-281" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(positive_corr_year<span class="sc">$</span>YEAR, positive_corr_year<span class="sc">$</span>correlation, <span class="at">sep =</span> <span class="st">" "</span>))</span>
<span id="cb76-282"><a href="#cb76-282" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-283"><a href="#cb76-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-284"><a href="#cb76-284" aria-hidden="true" tabindex="-1"></a><span class="fu">### </span></span>
<span id="cb76-285"><a href="#cb76-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-286"><a href="#cb76-286" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple"}</span>
<span id="cb76-287"><a href="#cb76-287" aria-hidden="true" tabindex="-1"></a><span class="fu">## Table 6: Experience</span></span>
<span id="cb76-288"><a href="#cb76-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-289"><a href="#cb76-289" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>We assume that if an analyst is monitoring a company for a long period of time, he/she is expected to make more informed predictions. Create a new column in NFLX3 called **experience** that counts the cumulative number of years the analyst monitor (have predictions) the company. Print the summary of experience column.</span>
<span id="cb76-290"><a href="#cb76-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-291"><a href="#cb76-291" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Hint:** Try to use cumsum() function in R.</span>
<span id="cb76-292"><a href="#cb76-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-293"><a href="#cb76-293" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Need Written Response in this callout:** Which analyst (s) has the highest number of **experience** in **NFLX3** dataset and for how long do they monitor the NFLX ticker?</span>
<span id="cb76-294"><a href="#cb76-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-295"><a href="#cb76-295" aria-hidden="true" tabindex="-1"></a>***`Two unique analyst with the following identifiers 72088 and 77748 had an hardcore experience of 17 years observing the NTFLX stock and making predictions based on the data provided.`***</span>
<span id="cb76-296"><a href="#cb76-296" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-297"><a href="#cb76-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-298"><a href="#cb76-298" aria-hidden="true" tabindex="-1"></a><span class="fu">## Your code for Task 6</span></span>
<span id="cb76-299"><a href="#cb76-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-300"><a href="#cb76-300" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb76-301"><a href="#cb76-301" aria-hidden="true" tabindex="-1"></a><span class="co"># Task 6: Experience</span></span>
<span id="cb76-302"><a href="#cb76-302" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate cumulative experience</span></span>
<span id="cb76-303"><a href="#cb76-303" aria-hidden="true" tabindex="-1"></a>NFLX3 <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span></span>
<span id="cb76-304"><a href="#cb76-304" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ANALYS) <span class="sc">%&gt;%</span></span>
<span id="cb76-305"><a href="#cb76-305" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">experience =</span> <span class="fu">cumsum</span>(<span class="sc">!</span><span class="fu">duplicated</span>(YEAR)))</span>
<span id="cb76-306"><a href="#cb76-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-307"><a href="#cb76-307" aria-hidden="true" tabindex="-1"></a><span class="co"># Find analyst(s) with the highest experience</span></span>
<span id="cb76-308"><a href="#cb76-308" aria-hidden="true" tabindex="-1"></a>max_experience <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span></span>
<span id="cb76-309"><a href="#cb76-309" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ANALYS) <span class="sc">%&gt;%</span></span>
<span id="cb76-310"><a href="#cb76-310" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">experience =</span> <span class="fu">max</span>(experience)) <span class="sc">%&gt;%</span></span>
<span id="cb76-311"><a href="#cb76-311" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(experience <span class="sc">==</span> <span class="fu">max</span>(experience)) <span class="sc">%&gt;%</span></span>
<span id="cb76-312"><a href="#cb76-312" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(experience))</span>
<span id="cb76-313"><a href="#cb76-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-314"><a href="#cb76-314" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary of the experience column</span></span>
<span id="cb76-315"><a href="#cb76-315" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NFLX3<span class="sc">$</span>experience)</span>
<span id="cb76-316"><a href="#cb76-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-317"><a href="#cb76-317" aria-hidden="true" tabindex="-1"></a><span class="co"># Print analyst(s) with the highest experience</span></span>
<span id="cb76-318"><a href="#cb76-318" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(max_experience)</span>
<span id="cb76-319"><a href="#cb76-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-320"><a href="#cb76-320" aria-hidden="true" tabindex="-1"></a><span class="co"># Define custom color palette</span></span>
<span id="cb76-321"><a href="#cb76-321" aria-hidden="true" tabindex="-1"></a>custom_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#66c2a5"</span>, <span class="st">"#fc8d62"</span>, <span class="st">"#8da0cb"</span>, <span class="st">"#e78ac3"</span>, <span class="st">"#a6d854"</span>, <span class="st">"#ffd92f"</span>, <span class="st">"#e5c494"</span>, <span class="st">"#b3b3b3"</span>)</span>
<span id="cb76-322"><a href="#cb76-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-323"><a href="#cb76-323" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualization with custom colors</span></span>
<span id="cb76-324"><a href="#cb76-324" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> max_experience, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(ANALYS, <span class="sc">-</span>experience), <span class="at">y =</span> experience, <span class="at">fill =</span> <span class="fu">reorder</span>(ANALYS, <span class="sc">-</span>experience))) <span class="sc">+</span></span>
<span id="cb76-325"><a href="#cb76-325" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb76-326"><a href="#cb76-326" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Analyst"</span>, <span class="at">y =</span> <span class="st">"Cumulative Experience"</span>) <span class="sc">+</span></span>
<span id="cb76-327"><a href="#cb76-327" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb76-328"><a href="#cb76-328" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> custom_colors)</span>
<span id="cb76-329"><a href="#cb76-329" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-330"><a href="#cb76-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-331"><a href="#cb76-331" aria-hidden="true" tabindex="-1"></a><span class="fu">### </span></span>
<span id="cb76-332"><a href="#cb76-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-333"><a href="#cb76-333" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple"}</span>
<span id="cb76-334"><a href="#cb76-334" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task 7: Size</span></span>
<span id="cb76-335"><a href="#cb76-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-336"><a href="#cb76-336" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>If a brokerage house has multiple analysts providing predictions for the same company, it may indicate a greater allocation of resources for company analysis. To capture this, create a new column in the <span class="in">`NFLX3`</span> dataset called <span class="in">`size`</span> that calculates the total count of **unique** analysts employed **per year** by **each** brokerage house (ESTIMATOR)</span>
<span id="cb76-337"><a href="#cb76-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-338"><a href="#cb76-338" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Need Written Response in this callout:** Print the frequencies for **size** variable. What does this frequency table reveal about the distribution of the number of analysts hired by brokerage houses in this dataset?</span>
<span id="cb76-339"><a href="#cb76-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-340"><a href="#cb76-340" aria-hidden="true" tabindex="-1"></a>***`We concluded that the number of analysts increase the frequency of hiring reduces exponentially. This indicates that with time the brokerage firm decided to hire an experience analyst per season to maximize productivity.`***</span>
<span id="cb76-341"><a href="#cb76-341" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-342"><a href="#cb76-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-343"><a href="#cb76-343" aria-hidden="true" tabindex="-1"></a><span class="fu">## Your code for Task 7</span></span>
<span id="cb76-344"><a href="#cb76-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-345"><a href="#cb76-345" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb76-346"><a href="#cb76-346" aria-hidden="true" tabindex="-1"></a> <span class="co"># Task 7: Size</span></span>
<span id="cb76-347"><a href="#cb76-347" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate analysts per year</span></span>
<span id="cb76-348"><a href="#cb76-348" aria-hidden="true" tabindex="-1"></a>NFLX3 <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span></span>
<span id="cb76-349"><a href="#cb76-349" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, ESTIMATOR) <span class="sc">%&gt;%</span></span>
<span id="cb76-350"><a href="#cb76-350" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">size =</span> <span class="fu">n_distinct</span>(ANALYS))</span>
<span id="cb76-351"><a href="#cb76-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-352"><a href="#cb76-352" aria-hidden="true" tabindex="-1"></a><span class="co"># Print frequencies</span></span>
<span id="cb76-353"><a href="#cb76-353" aria-hidden="true" tabindex="-1"></a>size_freq <span class="ot">&lt;-</span> <span class="fu">table</span>(NFLX3<span class="sc">$</span>size)</span>
<span id="cb76-354"><a href="#cb76-354" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(size_freq)</span>
<span id="cb76-355"><a href="#cb76-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-356"><a href="#cb76-356" aria-hidden="true" tabindex="-1"></a><span class="co"># Create frequency table</span></span>
<span id="cb76-357"><a href="#cb76-357" aria-hidden="true" tabindex="-1"></a>size_table <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(size_freq)</span>
<span id="cb76-358"><a href="#cb76-358" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(size_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Analysts"</span>, <span class="st">"Frequency"</span>)</span>
<span id="cb76-359"><a href="#cb76-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-360"><a href="#cb76-360" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort by frequency</span></span>
<span id="cb76-361"><a href="#cb76-361" aria-hidden="true" tabindex="-1"></a>size_table <span class="ot">&lt;-</span> size_table[<span class="fu">order</span>(<span class="sc">-</span>size_table<span class="sc">$</span>Frequency), ]</span>
<span id="cb76-362"><a href="#cb76-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-363"><a href="#cb76-363" aria-hidden="true" tabindex="-1"></a><span class="co"># Print sorted table using kableExtra</span></span>
<span id="cb76-364"><a href="#cb76-364" aria-hidden="true" tabindex="-1"></a>size_table <span class="sc">%&gt;%</span></span>
<span id="cb76-365"><a href="#cb76-365" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="st">"html"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb76-366"><a href="#cb76-366" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="at">full_width =</span> <span class="cn">FALSE</span>)</span>
<span id="cb76-367"><a href="#cb76-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-368"><a href="#cb76-368" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics</span></span>
<span id="cb76-369"><a href="#cb76-369" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NFLX3<span class="sc">$</span>size)</span>
<span id="cb76-370"><a href="#cb76-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-371"><a href="#cb76-371" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize results with different colors</span></span>
<span id="cb76-372"><a href="#cb76-372" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(size_table<span class="sc">$</span>Frequency, <span class="at">names.arg =</span> size_table<span class="sc">$</span>Analysts,</span>
<span id="cb76-373"><a href="#cb76-373" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Analysts"</span>, <span class="at">ylab =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb76-374"><a href="#cb76-374" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Analysts by Brokerage"</span>,</span>
<span id="cb76-375"><a href="#cb76-375" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"skyblue"</span>, <span class="st">"salmon"</span>, <span class="st">"lightgreen"</span>), <span class="at">border =</span> <span class="st">"black"</span>,</span>
<span id="cb76-376"><a href="#cb76-376" aria-hidden="true" tabindex="-1"></a>        <span class="at">las =</span> <span class="dv">1</span>, <span class="at">cex.names =</span> <span class="fl">0.8</span>)</span>
<span id="cb76-377"><a href="#cb76-377" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-378"><a href="#cb76-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-379"><a href="#cb76-379" aria-hidden="true" tabindex="-1"></a><span class="fu">### </span></span>
<span id="cb76-380"><a href="#cb76-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-381"><a href="#cb76-381" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple"}</span>
<span id="cb76-382"><a href="#cb76-382" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task 8: Prediction 1</span></span>
<span id="cb76-383"><a href="#cb76-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-384"><a href="#cb76-384" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>In the year 2020, NETFLIX reported an actual earnings per share (EPS) of \$6.08. To predict this EPS value based on historical data, we will employ a linear regression model using the dataset <span class="in">`NFLX3`</span> up until the year 2019. In this model, the target variable will be <span class="in">`ACTUAL`</span> and the predictor variables will include <span class="in">`VALUE`</span> and <span class="in">`past_accuracy`</span>. C.all your model as <span class="in">`model1.`</span></span>
<span id="cb76-385"><a href="#cb76-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-386"><a href="#cb76-386" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Need Written Response in this callout:** Using the linear regression model 'model1,' which has been trained on historical data up to the year 2019, what is the forecasted EPS (Earnings Per Share) for the year 2020? Please provide a brief explanation of the method you employed to make this prediction. If you encountered any challenges or were unable to make the calculation, briefly describe the specific issues you encountered.</span>
<span id="cb76-387"><a href="#cb76-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-388"><a href="#cb76-388" aria-hidden="true" tabindex="-1"></a>***Utilizing the linear regression model 'model1' trained on historical data until 2019, we can predict the Earnings Per Share (EPS) for 2020. The process involves assessing the model's goodness of fit, measured by the R-squared value. If the R-squared value surpasses 0.5, indicating a strong fit, the code calculates the mean of the 'past_accuracy' variable. When the fit is satisfactory, the model generates a forecast for the future period. This involves creating a new dataset with appropriate values for independent variables (VALUE and past_accuracy) and utilizing the 'predict' function to estimate the EPS. Conversely, if the R-squared value falls below the threshold, a warning message alerts that the model might not accurately predict future EPS. Addressing specific challenges related to data configuration or model training is essential to ensure the forecast's accuracy. This method enables accurate predictions under favorable model fit conditions, ensuring reliable forecasting outcomes.***</span>
<span id="cb76-389"><a href="#cb76-389" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-390"><a href="#cb76-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-391"><a href="#cb76-391" aria-hidden="true" tabindex="-1"></a><span class="fu">## Your code for Task 8</span></span>
<span id="cb76-392"><a href="#cb76-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-393"><a href="#cb76-393" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb76-394"><a href="#cb76-394" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean past_accuracy</span></span>
<span id="cb76-395"><a href="#cb76-395" aria-hidden="true" tabindex="-1"></a>mean_past_accuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(NFLX3<span class="sc">$</span>past_accuracy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb76-396"><a href="#cb76-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-397"><a href="#cb76-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-398"><a href="#cb76-398" aria-hidden="true" tabindex="-1"></a><span class="co"># Create linear regression model</span></span>
<span id="cb76-399"><a href="#cb76-399" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ACTUAL <span class="sc">~</span> VALUE <span class="sc">+</span> past_accuracy, <span class="at">data =</span> NFLX3)</span>
<span id="cb76-400"><a href="#cb76-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-401"><a href="#cb76-401" aria-hidden="true" tabindex="-1"></a><span class="co"># Get R-squared value</span></span>
<span id="cb76-402"><a href="#cb76-402" aria-hidden="true" tabindex="-1"></a>r_squared <span class="ot">&lt;-</span> <span class="fu">summary</span>(model1)<span class="sc">$</span>r.squared</span>
<span id="cb76-403"><a href="#cb76-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-404"><a href="#cb76-404" aria-hidden="true" tabindex="-1"></a><span class="co"># Check R-squared</span></span>
<span id="cb76-405"><a href="#cb76-405" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (r_squared <span class="sc">&gt;</span> <span class="fl">0.5</span>) {</span>
<span id="cb76-406"><a href="#cb76-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-407"><a href="#cb76-407" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create new data frame for future period</span></span>
<span id="cb76-408"><a href="#cb76-408" aria-hidden="true" tabindex="-1"></a>  new_data_future <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb76-409"><a href="#cb76-409" aria-hidden="true" tabindex="-1"></a>    <span class="at">VALUE =</span> <span class="fl">6.08</span>,</span>
<span id="cb76-410"><a href="#cb76-410" aria-hidden="true" tabindex="-1"></a>    <span class="at">past_accuracy =</span> mean_past_accuracy</span>
<span id="cb76-411"><a href="#cb76-411" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb76-412"><a href="#cb76-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-413"><a href="#cb76-413" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Predict EPS for future</span></span>
<span id="cb76-414"><a href="#cb76-414" aria-hidden="true" tabindex="-1"></a>  predicted_eps_future <span class="ot">&lt;-</span> <span class="fu">predict</span>(model1, <span class="at">newdata =</span> new_data_future)</span>
<span id="cb76-415"><a href="#cb76-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-416"><a href="#cb76-416" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Print forecasted EPS</span></span>
<span id="cb76-417"><a href="#cb76-417" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Forecasted EPS: $"</span>, <span class="fu">round</span>(predicted_eps_future, <span class="dv">2</span>))</span>
<span id="cb76-418"><a href="#cb76-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-419"><a href="#cb76-419" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb76-420"><a href="#cb76-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-421"><a href="#cb76-421" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Print warning</span></span>
<span id="cb76-422"><a href="#cb76-422" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Low R-squared value."</span>)</span>
<span id="cb76-423"><a href="#cb76-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-424"><a href="#cb76-424" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb76-425"><a href="#cb76-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-426"><a href="#cb76-426" aria-hidden="true" tabindex="-1"></a><span class="co"># Print mean past_accuracy</span></span>
<span id="cb76-427"><a href="#cb76-427" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Mean past_accuracy: "</span>, <span class="fu">round</span>(mean_past_accuracy, <span class="dv">2</span>))</span>
<span id="cb76-428"><a href="#cb76-428" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-429"><a href="#cb76-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-430"><a href="#cb76-430" aria-hidden="true" tabindex="-1"></a><span class="fu">### </span></span>
<span id="cb76-431"><a href="#cb76-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-432"><a href="#cb76-432" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple"}</span>
<span id="cb76-433"><a href="#cb76-433" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task 9: Prediction 2</span></span>
<span id="cb76-434"><a href="#cb76-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-435"><a href="#cb76-435" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>As an alternative approach, instead of modeling the 'ACTUAL' value, we can obtain the mean and median forecasts for the year 2020 as our best estimates of the EPS value for that year.</span>
<span id="cb76-436"><a href="#cb76-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-437"><a href="#cb76-437" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Need Written Response in this callout:** Please calculate these forecasts and then compare them with the results from the previous task. Finally, provide your insights and comments based on your findings.</span>
<span id="cb76-438"><a href="#cb76-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-439"><a href="#cb76-439" aria-hidden="true" tabindex="-1"></a>***In this alternative approach, we calculated both the mean and median forecasts for the year 2020 to estimate the EPS value. The mean forecast stood at approximately \$1.24, whereas the median forecast was notably lower, around \$0.41. Comparing these outcomes with the linear regression model used earlier, it becomes evident that the model-based forecast offers a more detailed and potentially accurate prediction. However, each method has its distinct advantages and disadvantages. The model-driven forecast considers historical relationships and variables like 'past_accuracy,' but its accuracy heavily depends on the quality of the model fit, indicated by the R-squared value. On the contrary, the mean and median forecasts provide straightforward summary statistics but might lack the predictive strength of a well-fitted model. The choice between these methods should be made considering the data quality and the specific context of the analysis.***</span>
<span id="cb76-440"><a href="#cb76-440" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-441"><a href="#cb76-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-442"><a href="#cb76-442" aria-hidden="true" tabindex="-1"></a><span class="fu">## Your code for Task 9</span></span>
<span id="cb76-443"><a href="#cb76-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-444"><a href="#cb76-444" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb76-445"><a href="#cb76-445" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean forecast</span></span>
<span id="cb76-446"><a href="#cb76-446" aria-hidden="true" tabindex="-1"></a>mean_forecast <span class="ot">&lt;-</span> <span class="fu">mean</span>(NFLX3<span class="sc">$</span>VALUE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb76-447"><a href="#cb76-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-448"><a href="#cb76-448" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate median forecast</span></span>
<span id="cb76-449"><a href="#cb76-449" aria-hidden="true" tabindex="-1"></a>median_forecast <span class="ot">&lt;-</span> <span class="fu">median</span>(NFLX3<span class="sc">$</span>VALUE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb76-450"><a href="#cb76-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-451"><a href="#cb76-451" aria-hidden="true" tabindex="-1"></a><span class="co"># Print forecasts</span></span>
<span id="cb76-452"><a href="#cb76-452" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Mean forecast: $"</span>, <span class="fu">round</span>(mean_forecast, <span class="dv">2</span>))</span>
<span id="cb76-453"><a href="#cb76-453" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Median forecast: $"</span>, <span class="fu">round</span>(median_forecast, <span class="dv">2</span>))</span>
<span id="cb76-454"><a href="#cb76-454" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-455"><a href="#cb76-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-456"><a href="#cb76-456" aria-hidden="true" tabindex="-1"></a><span class="fu">### </span></span>
<span id="cb76-457"><a href="#cb76-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-458"><a href="#cb76-458" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple"}</span>
<span id="cb76-459"><a href="#cb76-459" aria-hidden="true" tabindex="-1"></a><span class="fu">## Task 10: Averages</span></span>
<span id="cb76-460"><a href="#cb76-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-461"><a href="#cb76-461" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Generate a new dataset named <span class="in">`NFLX4`</span> by aggregating data from <span class="in">`NFLX3`</span> Include the variables <span class="in">`size`</span>, <span class="in">`experience`</span>, <span class="in">`horizon`</span>, <span class="in">`accuracy,`</span> <span class="in">`past_accuracy`</span>, and <span class="in">`ACTUAL`</span> in <span class="in">`NFLX4`</span>. When calculating the yearly averages for these variables, ignore any missing values (NAs). Present a summary of the <span class="in">`NFLX4`</span> dataset.</span>
<span id="cb76-462"><a href="#cb76-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-463"><a href="#cb76-463" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Need Written Response in this callout:** Subsequently, employ correlation analysis or exploratory data analysis to get insights into the relationships between these variables and 'ACTUAL,' if such relationships exist.</span>
<span id="cb76-464"><a href="#cb76-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-465"><a href="#cb76-465" aria-hidden="true" tabindex="-1"></a>***`Following an in-depth analysis of the NFLX4 dataset, significant patterns concerning the relationship between variables and 'ACTUAL' earnings per share have been uncovered. The correlation analysis indicated that 'ACTUAL' is positively linked with 'size' (0.18) and 'experience' (0.69), implying that larger and more experienced analyst groups tend to deliver more precise forecasts for 'ACTUAL'. Conversely, 'ACTUAL' exhibits negative correlations with 'horizon' (-0.63) and 'past_accuracy' (-0.80), indicating that analysts with longer forecasting periods and higher past accuracy often produce less accurate predictions for 'ACTUAL'. Visual representations through scatter plots reinforce these findings, such as the trend showing enhanced accuracy with an increase in the number of analysts in the 'ACTUAL' versus 'size' plot. These insights shed light on the factors influencing earnings per share forecasts, underscoring the importance of analyst group size and experience while emphasizing the potential drawbacks of longer forecasting horizons and overly accurate track records, crucial knowledge for financial analysts, investors, and decision-makers.`***</span>
<span id="cb76-466"><a href="#cb76-466" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-467"><a href="#cb76-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-468"><a href="#cb76-468" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=TRUE}</span></span>
<span id="cb76-469"><a href="#cb76-469" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate and calculate averages</span></span>
<span id="cb76-470"><a href="#cb76-470" aria-hidden="true" tabindex="-1"></a>NFLX4 <span class="ot">&lt;-</span> NFLX3 <span class="sc">%&gt;%</span></span>
<span id="cb76-471"><a href="#cb76-471" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb76-472"><a href="#cb76-472" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb76-473"><a href="#cb76-473" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fu">mean</span>(size, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb76-474"><a href="#cb76-474" aria-hidden="true" tabindex="-1"></a>    <span class="at">experience =</span> <span class="fu">mean</span>(experience, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb76-475"><a href="#cb76-475" aria-hidden="true" tabindex="-1"></a>    <span class="at">horizon =</span> <span class="fu">mean</span>(horizon, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb76-476"><a href="#cb76-476" aria-hidden="true" tabindex="-1"></a>    <span class="at">accuracy =</span> <span class="fu">mean</span>(accuracy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb76-477"><a href="#cb76-477" aria-hidden="true" tabindex="-1"></a>    <span class="at">past_accuracy =</span> <span class="fu">mean</span>(past_accuracy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb76-478"><a href="#cb76-478" aria-hidden="true" tabindex="-1"></a>    <span class="at">ACTUAL =</span> <span class="fu">mean</span>(ACTUAL, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb76-479"><a href="#cb76-479" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb76-480"><a href="#cb76-480" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-481"><a href="#cb76-481" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of NFLX4 dataset</span></span>
<span id="cb76-482"><a href="#cb76-482" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NFLX4)</span>
<span id="cb76-483"><a href="#cb76-483" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-484"><a href="#cb76-484" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a correlation matrix</span></span>
<span id="cb76-485"><a href="#cb76-485" aria-hidden="true" tabindex="-1"></a>correlation_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(NFLX4[, <span class="fu">c</span>(<span class="st">"size"</span>, <span class="st">"experience"</span>, <span class="st">"horizon"</span>, <span class="st">"accuracy"</span>, <span class="st">"past_accuracy"</span>, <span class="st">"ACTUAL"</span>)], <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb76-486"><a href="#cb76-486" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-487"><a href="#cb76-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-488"><a href="#cb76-488" aria-hidden="true" tabindex="-1"></a><span class="co"># Custom color palette</span></span>
<span id="cb76-489"><a href="#cb76-489" aria-hidden="true" tabindex="-1"></a>color_palette <span class="ot">&lt;-</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">"#FFFFFF"</span>, <span class="st">"#67a9cf"</span>, <span class="st">"#ef8a62"</span>, <span class="st">"#b2182b"</span>))(<span class="dv">100</span>)</span>
<span id="cb76-490"><a href="#cb76-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-491"><a href="#cb76-491" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a correlation plot with enhanced customization</span></span>
<span id="cb76-492"><a href="#cb76-492" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(</span>
<span id="cb76-493"><a href="#cb76-493" aria-hidden="true" tabindex="-1"></a>  correlation_matrix,</span>
<span id="cb76-494"><a href="#cb76-494" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"color"</span>,</span>
<span id="cb76-495"><a href="#cb76-495" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> color_palette,</span>
<span id="cb76-496"><a href="#cb76-496" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"upper"</span>,</span>
<span id="cb76-497"><a href="#cb76-497" aria-hidden="true" tabindex="-1"></a>  <span class="at">order =</span> <span class="st">"original"</span>,</span>
<span id="cb76-498"><a href="#cb76-498" aria-hidden="true" tabindex="-1"></a>  <span class="at">tl.cex =</span> <span class="fl">0.7</span>,  <span class="co"># Adjust the size of text labels</span></span>
<span id="cb76-499"><a href="#cb76-499" aria-hidden="true" tabindex="-1"></a>  <span class="at">cl.cex =</span> <span class="fl">0.8</span>,  <span class="co"># Adjust the size of correlation coefficients</span></span>
<span id="cb76-500"><a href="#cb76-500" aria-hidden="true" tabindex="-1"></a>  <span class="at">diag =</span> <span class="cn">FALSE</span>,</span>
<span id="cb76-501"><a href="#cb76-501" aria-hidden="true" tabindex="-1"></a>  <span class="at">number.cex =</span> <span class="fl">0.8</span></span>
<span id="cb76-502"><a href="#cb76-502" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-503"><a href="#cb76-503" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-504"><a href="#cb76-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-505"><a href="#cb76-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-506"><a href="#cb76-506" aria-hidden="true" tabindex="-1"></a><span class="co"># Print correlation matrix</span></span>
<span id="cb76-507"><a href="#cb76-507" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(correlation_matrix)</span>
<span id="cb76-508"><a href="#cb76-508" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-509"><a href="#cb76-509" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(NFLX4, <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">"size"</span>, <span class="st">"experience"</span>, <span class="st">"horizon"</span>, <span class="st">"accuracy"</span>, <span class="st">"past_accuracy"</span>, <span class="st">"ACTUAL"</span>))</span>
<span id="cb76-510"><a href="#cb76-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-511"><a href="#cb76-511" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-512"><a href="#cb76-512" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(NFLX4, <span class="fu">aes</span>(<span class="at">x =</span> size)) <span class="sc">+</span></span>
<span id="cb76-513"><a href="#cb76-513" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"#009999"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">bins =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb76-514"><a href="#cb76-514" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Distribution of Size"</span>) <span class="sc">+</span></span>
<span id="cb76-515"><a href="#cb76-515" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Size"</span>) <span class="sc">+</span></span>
<span id="cb76-516"><a href="#cb76-516" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb76-517"><a href="#cb76-517" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb76-518"><a href="#cb76-518" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-519"><a href="#cb76-519" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(NFLX4, <span class="fu">aes</span>(<span class="at">y =</span> size)) <span class="sc">+</span></span>
<span id="cb76-520"><a href="#cb76-520" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"#009999"</span>) <span class="sc">+</span></span>
<span id="cb76-521"><a href="#cb76-521" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Boxplot of Size"</span>) <span class="sc">+</span></span>
<span id="cb76-522"><a href="#cb76-522" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Size"</span>) <span class="sc">+</span></span>
<span id="cb76-523"><a href="#cb76-523" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb76-524"><a href="#cb76-524" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Made with <a href="https://quarto.org/">Quarto</a></div>   
    <div class="nav-footer-center"><a href="mailto:surya%20.SuryaVardhanMeka@my.unt.edu">Contact Surya Vardhan</a></div>
    <div class="nav-footer-right"><a href="https://github.com">Github Code Repo</a></div>
  </div>
</footer>



</body></html>